<<<<<<< HEAD
<<<<<<< HEAD
---
title: "Liz's Data Gathering"
author: "Liz Masten"
date: "10/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(WDI)
library(countrycode)
library(readr)
library(openxlsx)
library(janitor)
library(naniar)
library(forcats)
library(fastDummies)
library(tidyverse)

```


```{r Cian dataset}

# Cians' Second Draft Data which contains most of his predictors. 

third_draft <- read.xlsx("Raw_Data_Liz/Third_Draft.xlsx")


```

```{r Polity V}

# Polity V data- codebook in GitHub. 

polity <- read_csv("Raw_Data_Liz/p5v2018.csv", col_types = cols(
  .default = col_double(),
  scode = col_character(),
  country = col_character()
))

third_draft$year <- as.numeric(third_draft$year)

# These are all regime stability indicators either as-is or that I'll mutate later. 

polity <- polity %>% 
          select("country",
                "year",
                "fragment", 
                 "sf",
                 "change",
                 "regtrans",
                 "xrreg",
                 "xrcomp",
                 "xropen",
                 "parreg",
                 "parcomp",
                 "xconst",
                 "polity2",
                 "durable") %>% 
          filter(year >= 1960)

polity <- as.data.frame(polity)

# merge Polity with existing data from Cian. 

third_draft_polity <- merge(x = third_draft, y = polity, by = c("country", "year"), all = TRUE)

```

```{r}

# Try to find where thing's don't line up between datasets so far. 

# third_draft_polity has 27 more countries corresponding to 905 rows. See extra_co.rmd for list of countries. 

extra_countries_pol <- third_draft_polity[!third_draft_polity$country%in%third_draft$country,]

# Some should be renamed, others will be dropped later. There will be a ton more problem countries as we keep adding variables.  

```


```{r}

# GTD is the Global Terrorism Database. Codebook in GitHub. 

gtd <- read_csv("Raw_Data_Liz/gtd.csv")

# These are the terrorism indicators, which will take some manipulation. 

gtd_2 <- gtd %>% 
       select(country, country_txt, iyear, targtype1, nkill, nwound) %>% 
       select(!country) %>% 
       rename(country = country_txt,
              year = iyear)

```

```{r}

# Right now, targtype1 is a categorical variable with 22 different values. It's too granular for this project, so I'll recode the target type into state and nonstate targets.  

gtd_2$targtype1 <- as.factor(gtd_2$targtype1)


gtd_recode <- gtd_2 %>% 
              filter(targtype1 != 13) %>%  #13 and 20 are 'other' and 'unk,' respectively 
              filter(targtype1 != 20) %>% 
              mutate(recode_target1 = recode_factor(targtype1,
                                             "1" = "nonstate_target",   #businesses    
                                             "2" = "state_target",      #government(general)
                                             "3" = "state_target",      #police
                                             "4" = "state_target",      #military
                                             "5" = "nonstate_target",   #abortion-related
                                             "6" = "nonstate_target",   #airports, aircraft*
                                             "7" = "state_target",      #government(diplomats)
                                             "8" = "nonstate_target",   #edu institutions 
                                             "9" = "nonstate_target",   #food or water supply
                                             "10" = "nonstate_target",  #journalists/ media 
                                             "11" = "nonstate_target",  #maritime*
                                             "12" = "state_target",     #NGO
                                             "14" = "nonstate_target",  #private citizens/ property
                                             "15" = "nonstate_target",  #religious figures/ institutions
                                             "16" = "nonstate_target",  #telecommunications*
                                             "17" = "nonstate_target",  #terrorists/ non-state militias
                                             "18" = "nonstate_target",  #tourists 
                                             "19" = "nonstate_target",  #transportation 
                                             "21" = "nonstate_target",  #utilities*
                                             "22" = "state_target"      #violent political parties
                                             )) %>% 
  
  #create dummy columns to spread newly created observations into columns 
              dummy_cols(select_columns = "recode_target1") %>% 
  #this is junk I don't need 
              select(-targtype1, -recode_target1, -recode_target1_13, -recode_target1_20) %>% 
              group_by(year, country) %>% 
  #sum to account for n_kill per country per year
              mutate(terrorism_kill = sum(nkill)) %>% 
  #sum to account for n_wound per country per year 
              mutate(terrorism_wound = sum(nwound)) %>% 
              mutate(nonstate_target = sum(recode_target1_nonstate_target)) %>% 
              mutate(state_target = sum(recode_target1_state_target)) %>% 
  #deselect old pre-mutate variables 
              select(-nkill, -nwound, -recode_target1_nonstate_target, -recode_target1_state_target) %>% 
              distinct(country, year, .keep_all = TRUE)


  
```



```{r}

# Part II of keeping tabs on what countries don't match up. GTD has 205 unique country entries and our dataset so far has 217. 

extra_countries <- Data_Set6[!Data_Set6$country%in%gtd_2$country,]

find <- extra_countries %>% select(country) %>% 
       # group_by(country) %>% 
        #unique()

# Not included in GTD but included in Data_Set6 AFTER rename:

#American Samoa, Samoa, Aruba, Bermuda, Cape Verde, Curaçao, Micronesia, Faroe Islands, Gibraltar, Guam, Isle of Man, Channel Islands, Kiribati, Cayman Islands, Monaco, Saint Martin (French part), 	Macao SAR China, Northern Mariana Islands, Nauru, Puerto Rico, 	San Marino, São Tomé & Príncipe, Sint Maarten, Eswatini, 	Turks & Caicos Islands, St. Vincent & Grenadines, British Virgin Islands (28 total). 

```

```{r}

#The naming convention seemed better at the time, but this is Cian's data + Polity + my recode of GTD data. 

three_point_five <- merge(x = third_draft_polity, y = gtd_recode, by = c("country", "year"), all = TRUE)


write <- write_csv(three_point_five, path = "Raw_Data_Liz/three_point_five.csv")


```

```{r}

# UCPD/PRIO conflict data. Codebook in GitHub. 

conflict <- read_csv("Raw_Data_liz/ucdp-prio-acd-201.csv")

```

```{r}

# These are the conflict indicators. 

conflict_2 <- conflict %>% 
              select('location',
                     'year',
                     'intensity_level', 
                     'type_of_conflict') %>% 
  # To get rid of dyads. 
              filter(type_of_conflict != "2") %>% 
              rename("country" = "location") %>% 
  # TRUE/TRUE just to sum more easily later. No value in TRUE/TRUE. 
              mutate(recode_intensity = recode_factor(intensity_level,
                                                      "1" = "TRUE",
                                                      "2" = "TRUE")) %>%
              mutate(n_conflict = ifelse(recode_intensity =="TRUE", 1, 0)) %>% 
              select(-intensity_level, -recode_intensity, -type_of_conflict) %>% 
              group_by(country, year) %>% 
              summarise(n_conflict = sum(n_conflict))

```

```{r}

# Cian's data + Polity + GTD + UCPD

fourth_draft_data <- merge(x = three_point_five, y = conflict_2, by = c("country", "year"), all = TRUE)

```

```{r}

# Rename countries to make data line up. The World Bank data doesn't contain any historic countries. For example, North and South Vietnam are just coded as Vietnam in that dataset. Since this data represent the most consistent data we have, we pretty much have to continue this convention. 

rename_fourth_data <- fourth_draft_data %>% 
                      mutate(country = recode(country,
                            "Bosnia-Herzegovina" = "Bosnia & Herzegovina",     
                            "Cambodia (Kampuchea)" = "Cambodia",
                            "Madagascar (Malagasy)" = "Madagascar",   
                            "Russia (Soviet Union)" = "Russia",
                          #  "Serbia (Yugoslavia)" = "Yugoslavia"
                            "North Vietnam" = "Vietnam",
                            "South Vietnam" = "Vietnam",        
                            "Trinidad and Tobago" = "Trinidad & Tobago",    
                            "Vietnam (North Vietnam)" = "Vietnam",
                            "Vietnam (South Vietnam)" = "Vietnam",
                            "Vietnam North" = "Vietnam",
                            "Vietnam South" = "Vietnam",
                            "Yemen (North Yemen)" = "Yemen",
                            "South (South Yemen)" = "Yemen",
                            "North Yemen" = "Yemen",
                            "South Yemen" = "Yemen", 
                            "Yemen North" = "Yemen",
                            "Yemen South" = "Yemen",
                            "Zimbabwe (Rhodesia)" = "Zimbabwe",
                            "West Bank and Gaza Strip" = "Palestinian Territories",
                            "Zaire" = "Congo - Kinshasa",
                            "Democratic Republic of the Congo" = "Congo - Kinshasa",
                            "DR Congo (Zaire)" = "Congo - Kinshasa", 
                            "Congo Kinshasa" = "Congo - Kinshasa",
                            "Congo Brazzaville" = "Congo - Brazzaville", 
                            "People's Republic of the Congo" = "Congo - Brazzaville",
                            "Republic of the Congo" = "Congo - Brazzaville",
                            "Congo-Brazzaville" = "Congo - Brazzaville",
                            "Rhodesia" = "Zimbabwe", 
                            "Western Sahara" = "Morocco",
                            "Swaziland" = "Eswatini",
                            "Czech Republic" = "Czechia",
                            "Macau" = "Macao SAR China",
                            "East Timor" = "Timor - Leste",
                            "Timor Leste" = "Timor - Leste",
                            "Côte d’Ivoire" = "Ivory Coast",
                            "Cote D'Ivoire" = "Ivory Coast",
                            "Antigua and Barbuda" = "Antigua & Barbuda",
                            "Hong Kong" = "Hong Kong SAR China",
                            "Myanmar" = "Myanmar (Burma)",
                            "Korea South" = "South Korea",
                            "Korea North" = "North Korea",
                            "St. Kitts and Nevis" = "St. Kitts & Nevis",
                            "UAE" = "United Arab Emirates",
                            "United States of America" = "United States",
                          #this doubles with Sudan starting in 2011 
                            "Sudan-North" = "Sudan",
                            "Slovak Republic" = "Slovakia",
                            "Bosnia" = "Bosnia & Herzegovina",
                            "Serbia-Montenegro" = "Serbia and Montenegro"
                            )) %>% 
                      group_by(country, year)

# check to make sure all countries are changed 

ex_co <- rename_fourth_data[!rename_fourth_data$country%in%fourth_draft_data$country,]

find <- ex_co %>% select(country) %>% 
        group_by(country) %>% 
        unique()

# Spot check

v <- view(rename_fourth_data %>% 
     filter(country == "Yemen")) %>% 
     filter(year == "1964")

```

```{r}

# Remove countries that we either can't reconcile with the World Bank dataset. A lot of these problem countries are from GTD. For example, I'm removing Soviet Union because data aren't available to geolocate present-day countries to migrate those observations. However, it only appears in GTD so we're not really losing a lot. 

# We're also removing territories that aren't independent. Except for Palestine, we kept that one because it's a rich source of conflict data and also because we wanted to. 

rename_remove_fourth_data <- rename_fourth_data %>% 
                             filter(!country %in% c("Congo",
                                                "East Germany (GDR)",
                                                "West Germany (FRG)",
                                                "Germany East",
                                                "Germany West",
                                                "Taiwan",
                                                "Soviet Union",
                                                "New Hebrides",
                                                "Guadeloupe",
                                                "Martinique",
                                                "Vatican City",
                                                "French Guiana",
                                                "Falkland Islands",
                                                "Wallis and Futuna",
                                                "U.S. Virgin Islands",
                                                "Faroe Islands",
                                                "Vanuatu",
                                                "Channel Islands",
                                                "American Samoa",
                                                "British Virgin Islands",
                                                "Cayman Islands",
                                                "Curaçao",
                                                "French Polynesia",
                                                "Gibraltar", 
                                                "Guam",
                                                "Hyderabad",
                                                "International",
                                                "Isle of Man",
                                                "Mauritania, Morocco",
                                                "New Caledonia",
                                                "Northern Mariana Islands",
                                                "Saint Martin (French part)",
                                                "Sint Maarten",
                                                "Solomon Islands",
                                                "Turks & Caicos Islands",
                                                "Puerto Rico",
                                                "USSR",
                                                "Soviet Union"
                                                ))

unique(rename_remove_fourth_data$country)

```



```{r}

# Here's the data with counries cleaned up. 

fourth_final <- write_csv(rename_remove_fourth_data, path = "Raw_Data_Liz/fourth_final.csv")

fourth_final$n_conflict <- as.numeric(fourth_final$n_conflict)

fourth_final$n_conflict[is.na(fourth_final$n_conflict)] = 0

ff <- fourth_final %>% mutate(n_conflict = sum(n_conflict))

# combine unique country/year observations into one observation:  

ff_2 <- ff %>%
  group_by(country, year) %>%
  fill(everything(), .direction = "down") %>%
  fill(everything(), .direction = "up") %>%
  slice(1)

# spot check for weirdness: 

check_1 <- ff_2 %>% filter(country == "Sudan") #looks ok 

check_2 <- ff_2 %>% filter(country == "Yemen") #looks ok 

check_3 <- ff_2 %>% filter(country == "Germany") #looks ok 

```


```{r}

# Fourth dataset, but cleaner. 

fifth <- write_csv(ff_2, path = "Raw_Data_Liz/fifth.csv")

```

```{r}

six <- read_csv("Raw_Data_Liz/sixth.csv", col_types = cols(
  .default = col_double(),
  country = col_character(),
  iso2c = col_character(),
  continent = col_character()
))

# get rid of random years before 1960

six_2 <- six %>% 
         filter(year >= 1960)

# In Excel because it was just easier: Deleted South Sudan pre 2011
# Deleted 4 instances of Serbia (Yugoslavia) bc no meaningful data
# Combined data for Czechia and Slovakia between 1960-1992 into Czechoslovakia; deleted those observations before 1992
# Last observation for Czechoslovakia is 1992; other two start at 1993 

```

```{r}

# write sixth dataset with changes

sixth_final <- write_csv(six_2, path = "Raw_Data_Liz/sixth_final.csv")

# Realize that Cian did the same thing and saved it as Final_Data, so I copy-pasted my changes into that dataset. Final_Data is our final data. 

```



